### ISSUE TITLE
Using object for Options instead of array

### ISSUE THREAD

**Issue by xon52** [sagalbot/vue-select#333] opened 2017-10-08 05:25 UTC
I really like this project, but any chance it could support objects as the options? Object keys mapped to the select option value, and the object values as the select option text?
The objects which I want to include are in the form:
`export const DriverLicences = {
	'c':'C - Car',
	'lr':'LR - Light Rigid',
	'mr':'MR - Medium Rigid',
...`

**Comment by Sopamo** [comment] 2017-10-10 11:00
This seems to be a duplicate of https://github.com/sagalbot/vue-select/issues/122

See https://trello.com/c/Hk0NmkaQ/15-optionally-return-a-specific-key-from-selected-objects as well.

You might be able to solve this with a computed variable with a set and get method.

**Comment by xon52** [comment] 2017-10-10 12:34
Hey thanks. Sorry, I couldn't find any reference to this.
Good idea with the computed variables. I'll have a play with that. Thanks.

**Comment by gthuo** [comment] 2017-11-08 09:07
#22

**Closed** 2019-03-23 17:48 UTC
