### ISSUE TITLE
Fix for IE scrollbar closing bug causes unclosable drop-down on all browsers

### ISSUE THREAD

**Issue by pippinsoft** [sagalbot/vue-select#667] opened 2018-10-03 04:19 UTC
The fix in #373 has an unfortunate side-effect: the drop-down can become permanently stuck open.

To reproduce:

1. go to the multi-select codepen: https://codepen.io/sagalbot/pen/opMGro
2. click the down arrow to show options
3. click the scrollbar
4. click the background (entirely away from the control)
5. the drop-down cannot be closed

I was able to solve it by replacing `@mousedown` with  `@mouseenter` and `@mouseleave`, which set and clear a flag (`isMouseOver`) respectively. I then test for `isMouseOver` in `onSearchBlur`:

```
      onSearchBlur() {
        if (this.isMouseOver) {
          this.$refs.search.focus()
        } else {
          if (this.clearSearchOnBlur) {
            this.search = ''
          }
          this.open = false
          this.$emit('search:blur')
        }
      },
```

However, I do not use `closeOnSelect`, have not tested with it set, and **I suspect that this will not work with it set**. Also, **it breaks `onEscape`** -- the escape key will not close the drop-down while the mouse is over it.

Without `this.$refs.search.focus()`, the problem persists on IE, making this a little clunky.

**Comment by crisleiria** [comment] 2018-10-08 14:01
I was able to reproduce here also, very annoying bug. Affects all browsers and single select configuration also.

**Comment by franciscotrillo** [comment] 2018-10-11 10:08
I also encountered this bug.
Once you've clicked on the scrollbar, the dropdown wont close when clicking away.

**Comment by tomaswitek** [comment] 2018-10-15 14:08
The main problem is loosing the focus on search when clicking the dropdown on IE and Edge.
This small fix https://github.com/sagalbot/vue-select/pull/682 should resolve the problem.

**Comment by adi518** [comment] 2018-12-05 23:56
Oh, sorry about this regression. Looks like the fix was easy though. @montananyto-dev The PR that fixes this issue isn't merged yet.

**Closed** 2019-05-03 21:37 UTC
