### ISSUE TITLE
Fix to show tho lines. Search input spread out selector.

### ISSUE THREAD

**Issue by psy21d** [sagalbot/vue-select#514] opened 2018-04-18 19:40 UTC
![search](https://user-images.githubusercontent.com/11248900/38954050-4b769fcc-4359-11e8-8abb-58e4eb665c7a.png)

![search2](https://user-images.githubusercontent.com/11248900/38954160-9d6164fc-4359-11e8-97ae-84669d460173.png)

If I make it small, the click does not go through the inscription, despite the fact that the mode is selected not by tags, but by one selector:
![search3](https://user-images.githubusercontent.com/11248900/38955323-fede0912-435c-11e8-80e5-1d0f0a3bbba5.png)

I not need to make this wider.
But if i click in input box, this problem vanish (tag disappears)

Please, fix it somehow

**Comment by BasConijn** [comment] 2018-04-23 08:34
Duplicate of #225.
Can be fixed by applying the css in the comment of MohammadSabbagh.

**Closed** 2019-03-24 21:59 UTC
